# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ip_integrator/ip_integrator.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_integrator || ORIG_REF_NAME==ip_integrator} -quiet] -quiet

# IP: bd/ip_integrator/ip/ip_integrator_processing_system7_0_0/ip_integrator_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_integrator_processing_system7_0_0 || ORIG_REF_NAME==ip_integrator_processing_system7_0_0} -quiet] -quiet

# IP: bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/ip_integrator_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_integrator_smartconnect_0_0 || ORIG_REF_NAME==ip_integrator_smartconnect_0_0} -quiet] -quiet

# Block Designs: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/bd_d914.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_0/bd_d914_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_1/bd_d914_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_2/bd_d914_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_3/bd_d914_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_4/bd_d914_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_5/bd_d914_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_6/bd_d914_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_7/bd_d914_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_8/bd_d914_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_9/bd_d914_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_10/bd_d914_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_11/bd_d914_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_12/bd_d914_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_13/bd_d914_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_14/bd_d914_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_15/bd_d914_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_16/bd_d914_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_17/bd_d914_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_18/bd_d914_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_19/bd_d914_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_20/bd_d914_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_21/bd_d914_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_22/bd_d914_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_23/bd_d914_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_24/bd_d914_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_25/bd_d914_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_26/bd_d914_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_27/bd_d914_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_28/bd_d914_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_29/bd_d914_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_30/bd_d914_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_31/bd_d914_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_32/bd_d914_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_33/bd_d914_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_34/bd_d914_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_35/bd_d914_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_36/bd_d914_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/ip_integrator/ip/ip_integrator_axi_bram_ctrl_0_0/ip_integrator_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_integrator_axi_bram_ctrl_0_0 || ORIG_REF_NAME==ip_integrator_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/ip_integrator/ip/ip_integrator_axi_bram_ctrl_1_0/ip_integrator_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_integrator_axi_bram_ctrl_1_0 || ORIG_REF_NAME==ip_integrator_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/ip_integrator/ip/ip_integrator_blk_mem_gen_0_0/ip_integrator_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_integrator_blk_mem_gen_0_0 || ORIG_REF_NAME==ip_integrator_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/ip_integrator/ip/ip_integrator_blk_mem_gen_0_1/ip_integrator_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_integrator_blk_mem_gen_0_1 || ORIG_REF_NAME==ip_integrator_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/ip_integrator/ip/ip_integrator_axi_gpio_0_0/ip_integrator_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_integrator_axi_gpio_0_0 || ORIG_REF_NAME==ip_integrator_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ip_integrator/ip/ip_integrator_proc_sys_reset_0_0/ip_integrator_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_integrator_proc_sys_reset_0_0 || ORIG_REF_NAME==ip_integrator_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ip_integrator/ip/ip_integrator_rv_sc_ip_0_0/ip_integrator_rv_sc_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_integrator_rv_sc_ip_0_0 || ORIG_REF_NAME==ip_integrator_rv_sc_ip_0_0} -quiet] -quiet

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_processing_system7_0_0/ip_integrator_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ip_integrator_processing_system7_0_0 || ORIG_REF_NAME==ip_integrator_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_1/bd_d914_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_1/bd_d914_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_2/bd_d914_arsw_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_3/bd_d914_rsw_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_4/bd_d914_awsw_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_5/bd_d914_wsw_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_6/bd_d914_bsw_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_10/bd_d914_s00a2s_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_11/bd_d914_sarn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_12/bd_d914_srn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_13/bd_d914_sawn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_14/bd_d914_swn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_15/bd_d914_sbn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_16/bd_d914_m00s2a_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_17/bd_d914_m00arn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_18/bd_d914_m00rn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_19/bd_d914_m00awn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_20/bd_d914_m00wn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_21/bd_d914_m00bn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_23/bd_d914_m01s2a_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_24/bd_d914_m01arn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_25/bd_d914_m01rn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_26/bd_d914_m01awn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_27/bd_d914_m01wn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_28/bd_d914_m01bn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_30/bd_d914_m02s2a_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_31/bd_d914_m02arn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_32/bd_d914_m02rn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_33/bd_d914_m02awn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_34/bd_d914_m02wn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/bd_0/ip/ip_35/bd_d914_m02bn_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_smartconnect_0_0/ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_blk_mem_gen_0_0/ip_integrator_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_blk_mem_gen_0_1/ip_integrator_blk_mem_gen_0_1_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_axi_gpio_0_0/ip_integrator_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ip_integrator_axi_gpio_0_0 || ORIG_REF_NAME==ip_integrator_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_axi_gpio_0_0/ip_integrator_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_axi_gpio_0_0/ip_integrator_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ip_integrator_axi_gpio_0_0 || ORIG_REF_NAME==ip_integrator_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_proc_sys_reset_0_0/ip_integrator_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ip_integrator_proc_sys_reset_0_0 || ORIG_REF_NAME==ip_integrator_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip/ip_integrator_proc_sys_reset_0_0/ip_integrator_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ip_integrator_proc_sys_reset_0_0 || ORIG_REF_NAME==ip_integrator_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/tbnrs/Documents/Development/hdl_group_project_sc/hdl_group_project.gen/sources_1/bd/ip_integrator/ip_integrator_ooc.xdc
